config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :sessions => 'users/sessions', registrations: 'registrations' }, :path_prefix => ''
  resources :contacts
  resources "touchs", only: [:new, :create]
  resources :users
  namespace :admin do
    resources :users
  end

  get 'home/home'
  get 'home/about'
  get 'home/sitemap'
  get 'home/amp'

  namespace :blogs do
    get '/' => 'toppage#index'
    get ':name' => 'categories#show', as: 'category_show'
    resources :categories
    resources :posts do
      resources :comments
    end
    get ':seo_name/:id' => 'posts#show', as: 'post_detail'
  end

  root 'home#home'

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  post_id    :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/controllers/blogs/categories_controller.rb
class Blogs::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  impressionist
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.all.order('id')
    @posts = Post.all
    @most_views = Post.order('view DESC').first(8)
    @newest_views = Post.order('created_at DESC').first(4)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit;end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by_name(params[:name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/blogs/comments_controller.rb
class Blogs::CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end
  def update;end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
    if @comment.save
      format.html { redirect_to blogs_post_detail_path(@post.title.to_url, @post.id), notice: 'Post was successfully created.' }
    else
      flash.now[:danger] = "error"
    end
  end
  end
  def show
    @comment = comment.find(params[:id])
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:post_id, :content, :user_id)
  end
end

app/controllers/blogs/posts_controller.rb
class Blogs::PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action:authenticate_user!, :except => [:show, :index]
  impressionist
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @category = Category.find_by_id(@post.category_id)
    @categories = Category.all.order('id')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all
    @post = Post.find_by_id(params[:id])
    @category = Category.find_by_id(@post.category_id)
    @categories = Category.all.order('id')
    @post.view += 1
    @post.save!
  end

  # GET /posts/new
  def new
      @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit;end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.view = 0
    respond_to do |format|
      if @post.save
        format.html { redirect_to blogs_post_detail_path(@post.title.to_url, @post.id), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to blogs_post_detail_path(@post.title.to_url, @post.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :picture, :view,:category_id)
    end
end

app/controllers/blogs/toppage_controller.rb
class Blogs::ToppageController < ApplicationController

  def index
    @posts = Post.all
    @most_views = Post.order('view DESC').first(8)
    @newest_views = Post.order('created_at DESC').first(4)
    @categories = Category.all.order('id')
    @category = Category.first
    # @source = Nokogiri::HTML(@post.body)
    # @img = @source.css('img').map{ |i| i['src'] }.first
  end

end

app/controllers/comments_controller.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  post_id    :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(params.require(:comment).permit!)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blogs_post_path(@post), notice: 'Comment was successfully created.' }
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :content)
    end
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  post_id    :integer
#  content    :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

module CommentsHelper
end

app/views/blogs/comments/_comment.html.erb
<%= div_for(comment) do %>
  <p>
    <%= h(comment.content) %></br>
     &nbsp;<small>Posted : <%= time_ago_in_words(comment.created_at) %>, By : <%= comment.user.email%></small></br>
  </p>
<% end %>

app/views/blogs/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blogs/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', blogs_post_comment_path(@comment) %> |
<%= link_to 'Back', blogs_post_comments_path %>

app/views/blogs/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.content %></td>
        <td><%= link_to 'Show', blogs_post_comment_path(comment) %></td>
        <td><%= link_to 'Edit', edit_blogs_post_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', blogs_post_comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_blogs_post_comment_path %>

app/views/blogs/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', blogs_post_comments_path %>

app/views/blogs/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @comment.content %>
</p>

<%= link_to 'Edit', edit_blogs_post_comment_path(@comment) %> |
<%= link_to 'Back', blogs_post_comments_path %>