config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :sessions => 'users/sessions', registrations: 'registrations' }, :path_prefix => ''
  resources :contacts
  resources "touchs", only: [:new, :create]
  resources :users
  namespace :admin do
    resources :users
  end

  get 'home/home'
  get 'home/about'
  get 'home/sitemap'
  get 'home/amp'

  namespace :blogs do
    get '/' => 'toppage#index'
    get ':name' => 'categories#show', as: 'category_show'
    resources :categories
    resources :posts do
      resources :comments
    end
    get ':seo_name/:id' => 'posts#show', as: 'post_detail'
  end

  root 'home#home'

end

app/controllers/blogs/categories_controller.rb
class Blogs::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  impressionist
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.all.order('id')
    @posts = Post.all
    @most_views = Post.order('view DESC').first(8)
    @newest_views = Post.order('created_at DESC').first(4)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit;end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by_name(params[:name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/blogs/comments_controller.rb
class Blogs::CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end
  def update;end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
    if @comment.save
      format.html { redirect_to blogs_post_detail_path(@post.title.to_url, @post.id), notice: 'Post was successfully created.' }
    else
      flash.now[:danger] = "error"
    end
  end
  end
  def show
    @comment = comment.find(params[:id])
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:post_id, :content, :user_id)
  end
end

app/controllers/blogs/posts_controller.rb
class Blogs::PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action:authenticate_user!, :except => [:show, :index]
  impressionist
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @category = Category.find_by_id(@post.category_id)
    @categories = Category.all.order('id')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all
    @post = Post.find_by_id(params[:id])
    @category = Category.find_by_id(@post.category_id)
    @categories = Category.all.order('id')
    @post.view += 1
    @post.save!
  end

  # GET /posts/new
  def new
      @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit;end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.view = 0
    respond_to do |format|
      if @post.save
        format.html { redirect_to blogs_post_detail_path(@post.title.to_url, @post.id), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to blogs_post_detail_path(@post.title.to_url, @post.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :picture, :view,:category_id)
    end
end

app/controllers/blogs/toppage_controller.rb
class Blogs::ToppageController < ApplicationController

  def index
    @posts = Post.all
    @most_views = Post.order('view DESC').first(8)
    @newest_views = Post.order('created_at DESC').first(4)
    @categories = Category.all.order('id')
    @category = Category.first
    # @source = Nokogiri::HTML(@post.body)
    # @img = @source.css('img').map{ |i| i['src'] }.first
  end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/blogs/toppage/_latestpost.html.slim
.content.container-fluid
  // .searchbox
  //   form#search action="/search" method="get"
  //     input name="q" placeholder="Search..." type="text"
  .col-lg-3.no-padding
    .title
      - if @category != nil
        h3 #{@category.name.capitalize}
        p In this section you will find in-depth how-tos involving common web development and web design techniques.
      - else
        h3 Blogs
        p In this section you will find in-depth how-tos involving common web development and web design techniques.
    .secondblog
      = image_tag(@most_views.first.picture)
      = link_to @most_views.first.title, blogs_post_detail_path(@most_views.first.title.to_url, @most_views.first.id)
  .col-lg-9.no-padding
    .firstblog
      = image_tag(@newest_views.first.picture)
      = link_to @newest_views.first.title, blogs_post_detail_path(@newest_views.first.title.to_url, @newest_views.first.id)

  .navigation
    ul
      li
        h3 Most View
        p Top blog of sharing category

  - @most_views.each  do |post|
    .blogs
      = image_tag(post.picture)
      = link_to post.title, blogs_post_detail_path(post.title.to_url, post.id)

  .navigation
    ul
      li
        h3 Newest
        p Recents blog of sharing category

  - @newest_views.each do |post|
    .blogs
      = image_tag(post.picture)
      = link_to post.title, blogs_post_detail_path(post.title.to_url, post.id)
section#footer.footer-section
  .inner-container
    = render "home/footer"

app/views/blogs/toppage/_mostview.html.slim
// .content
//   .col-lg-4.no-padding
//     .latestspost
//       //this is latests post
//       = image_tag asset_path('voluntee.png')
//       .content.no-padding
//         = link_to 'detail.html', :title => "http://localhost:3000/blogpage/details" do
//           h3 Time To Work Social
//         end

//         ul.no-padding
//           li
//             = image_tag asset_path('calendar.png'), :class => "logo"
//           li
//             p 02 Jan 2016
//           li
//             = image_tag asset_path('comment.png'), :class => "logo"
//           li
//             p 2 comments
//         p In the first chapter we discussed how to build communities. Many of the communities you can build online are social media communities. In this chapter, we’re going to discuss some key ways you can build traffic to your blog once you have your social media communities established. Most people assume that social media sharing is easy.
//   .col-lg-4.no-padding
//     .latestspost
//       //this is latests post
//       = image_tag asset_path('voluntee1.png')
//       .content.no-padding
//         = link_to 'detail.html', :title => "http://localhost:3000/blogpage/details" do
//           h3 Time To Work Social
//         end
//         ul.no-padding
//           li
//             = image_tag asset_path('calendar.png'), :class => "logo"
//           li
//             p 02 Jan 2016
//           li
//             = image_tag asset_path('comment.png'), :class => "logo"
//           li
//             p 2 comments
//         p In the first chapter we discussed how to build communities. Many of the communities you can build online are social media communities. In this chapter, we’re going to discuss some key ways you can build traffic to your blog once you have your social media communities established. Most people assume that social media sharing is easy.
//   .col-lg-4.no-padding
//     .mostviewpost
//       // this is mostview

//       h3 Most View
//       - 3.times do
//         = image_tag asset_path('voluntee1.png')
//         .content_mostview.no-padding
//           = link_to 'detail.html', :title => "http://localhost:3000/blogpage/details" do
//             h4 Time To Work Social
//           end
//           ul.no-padding
//             li
//               = image_tag asset_path('calendar.png'), :class => "logo"
//             li
//               p 02 Jan 2016
//             li
//               = image_tag asset_path('comment.png'), :class => "logo"
//             li
//               p 2 comments

//   //another raw
//   .col-lg-4.no-padding
//     .latestspost
//       //this is latests post
//       = image_tag asset_path('voluntee.png')
//       .content.no-padding
//         = link_to 'detail.html', :title => "http://localhost:3000/blogpage/details" do
//           h3 Time To Work Social
//         end
//         ul.no-padding
//           li
//             = image_tag asset_path('calendar.png'), :class => "logo"
//           li
//             p 02 Jan 2016
//           li
//             = image_tag asset_path('comment.png'), :class => "logo"
//           li
//             p 2 comments
//         p In the first chapter we discussed how to build communities. Many of the communities you can build online are social media communities. In this chapter, we’re going to discuss some key ways you can build traffic to your blog once you have your social media communities established. Most people assume that social media sharing is easy.

//   .col-lg-4.no-padding
//     .latestspost
//       //this is latests post
//       = image_tag asset_path('voluntee1.png')
//       .content.no-padding
//         = link_to 'detail.html', :title => "http://localhost:3000/blogpage/details" do
//           h3 Time To Work Social
//         end
//         ul.no-padding
//           li
//             = image_tag asset_path('calendar.png'), :class => "logo"
//           li
//             p 02 Jan 2016
//           li
//             = image_tag asset_path('comment.png'), :class => "logo"
//           li
//             p 2 comments
//         p In the first chapter we discussed how to build communities. Many of the communities you can build online are social media communities. In this chapter, we’re going to discuss some key ways you can build traffic to your blog once you have your social media communities established. Most people assume that social media sharing is easy.
//   .col-lg-4.no-padding
//     .subcribe
//       // this is subcribe
//       form role="form"
//         .form-group
//           input#inputlg.form-control.input-lg placeholder="Name" type="text"
//           input#inputlg.form-control.input-lg placeholder="Email" type="text"
//       button.btn.btn_round.btn_blue SUBCRIBE


//- arrays


.main-container
  h1 Colorful CSS Buttons
  button.btn.btn-blue.btn-border-rev hello
  button.btn.btn-purple.btn-border-rev Chao
  // each name,type in btnTypes
  //   section
  //     h2= name
  //     each text,color in btnColors
  //       button class="btn btn-"+color+" btn-"+type

app/views/blogs/toppage/_navigate.html.slim
.content
  = link_to root_path do
    .logo
      .image-logo
        = image_tag 'logo.png', :alt => "Golden Owl Consulting"
      .title-logo
        h1.title-main Golden Owl
  end
  .category
    ul
      // - @categories.each do |cate|
      //   - if @category.name == cate.name
      //     li.category-menu.active
      //       = link_to blogs_category_show_path(cate.name)
      //         i class="fa fa-pencil fa-3x"
      //   - else
      //     li.category-menu
      //       = link_to blogs_category_show_path(cate.name)
      //         i class="fa fa-pencil fa-3x"
      - if @category.blank?
        li.category-menu
          = link_to blogs_path
            i class="fa fa-pencil fa-3x"
            .circle
        li.category-menu
          = link_to blogs_category_show_path("sharing")
            i class="fa fa-heart-o fa-3x"
            .circle
        li.category-menu
          = link_to blogs_category_show_path("frontend")
            i class="fa fa-mobile fa-3x"
            .circle
        li.category-menu
          = link_to blogs_category_show_path("ror")
            i class="fa fa-diamond fa-3x"

      - else
        - if @category.name == @categories.first.name
          li.category-menu.active
            = link_to blogs_path, title: "Blogs"
              i class="fa fa-pencil fa-3x"
              .circle
        - else
          li.category-menu
            = link_to blogs_path, title: "Blogs"
              i class="fa fa-pencil fa-3x"
              .circle
        - if @category.name == @categories.second.name
          li.category-menu.active
            = link_to blogs_category_show_path(@categories.second.name), title: "Sharing"
              i class="fa fa-heart-o fa-3x"
              .circle
        - else
          li.category-menu
            = link_to blogs_category_show_path(@categories.second.name), title: "Sharing"
              i class="fa fa-heart-o fa-3x"
              .circle
        - if @category.name == @categories.third.name
          li.category-menu.active
            = link_to blogs_category_show_path(@categories.third.name), title: "Frontend"
              i class="fa fa-laptop fa-3x"
              .circle
        - else
          li.category-menu
            = link_to blogs_category_show_path(@categories.third.name), title: "Frontend"
              i class="fa fa-laptop fa-3x"
              .circle
        - if  @category.name == @categories.fourth.name
          li.category-menu.active
            = link_to blogs_category_show_path(@categories.fourth.name), title: "Ruby on Rails"
              i class="fa fa-diamond fa-3x"
              .circle
        - else
          li.category-menu
            = link_to blogs_category_show_path(@categories.fourth.name), title: "Ruby on Rails"
              i class="fa fa-diamond fa-3x"
        li.show-category-name
          - @categories.each do |cate|
            - if @category.name == cate.name
                p.active #{cate.name.capitalize}
            - else
                p #{cate.name.capitalize}
      // .blog.active
      //   p Blog
      // .sharing
      //   p Sharing
      // .fontend
      //   p Fontend
      // .ror
      //   p RoR
      // li
      //   .searchbox
      //     form#search action="/search" method="get"
      //       input name="q" placeholder="Search..." type="text"
        // .lang
        //   =link_to "E", root_path
        //   =link_to "V", root_path
      // = button_to  "Login",new_user_session_path,:class =>"btn btn-purple btn-border-rev"
      // button.btn.btn-purple.btn-border-rev Chao
      .user
        - if user_signed_in?
          = link_to "Hi " + current_user.email, edit_user_registration_path, :class => "btn btn-purple btn-border-rev"
          div class="btn-group"
            button class="btn btn-blue btn-signup" data-toggle="dropdown"
                i class="fa fa-caret-down"
            ul class="dropdown-menu pull-right" role="menu"
              li
                = link_to edit_user_registration_path
                  i class="fa fa-cog"
                  | Setting
              li
                = link_to user_path(current_user)
                  i class="fa fa-user"
                  | Profile
              li class="divider"
              li
                = link_to  destroy_user_session_path, :method => :delete
                  i class="fa fa-sign-out" title = "Sign Out"
                  | Sign Out
          div class="btn-group"
            button class="btn btn-red btn-signup" data-toggle="dropdown"
                i class="fa fa-plus-circle"
            ul class="dropdown-menu pull-right" role="menu"
              li
                = link_to new_blogs_post_path
                  i class="fa  fa-plus-square-o"
                  | New Post

        - else
          = link_to "Sign Up", new_user_registration_path, :class => "btn btn-purple btn-signup"
          .dropdown
            button class="btn btn-blue btn-signup" data-toggle="dropdown" Sign In
            ul class="dropdown-menu pull-right" role="menu"
              li
                = form_for(:user, :url => session_path(:user), html: { role: "form" }) do |f|
                  .form-group
                    = f.label :email
                    = f.email_field :email, autofocus: true, class: "form-control"
                  .form-group
                    = f.label :password
                    = f.password_field :password, autocomplete: "off", class: "form-control"
                    .help-block.text-right
                      a href=""  Forget the password ?
                    = f.submit  t('.sign_in', :default => "Sign in"), class: "btn btn-primary"

app/views/blogs/toppage/index.html.slim
section#navigate.navigate-section
  .inner-container
    = render "navigate"
section#latestpost.latestpost-section
  .inner-container
    = render "latestpost"