config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users, :controllers => { :sessions => 'users/sessions', registrations: 'registrations' }, :path_prefix => ''
  resources :contacts
  resources "touchs", only: [:new, :create]
  resources :users
  namespace :admin do
    resources :users
  end

  get 'home/home'
  get 'home/about'
  get 'home/sitemap'
  get 'home/amp'

  namespace :blogs do
    get '/' => 'toppage#index'
    get ':name' => 'categories#show', as: 'category_show'
    resources :categories
    resources :posts do
      resources :comments
    end
    get ':seo_name/:id' => 'posts#show', as: 'post_detail'
  end

  root 'home#home'

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  picture     :string
#  view        :integer
#  category_id :integer
#

class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category
  has_many :comments, dependent: :destroy
  mount_uploader :picture, PictureUploader
  is_impressionable :column_name => :impressions_count
end

app/controllers/blogs/categories_controller.rb
class Blogs::CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  impressionist
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @categories = Category.all.order('id')
    @posts = Post.all
    @most_views = Post.order('view DESC').first(8)
    @newest_views = Post.order('created_at DESC').first(4)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit;end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by_name(params[:name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/blogs/comments_controller.rb
class Blogs::CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end
  def update;end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
    if @comment.save
      format.html { redirect_to blogs_post_detail_path(@post.title.to_url, @post.id), notice: 'Post was successfully created.' }
    else
      flash.now[:danger] = "error"
    end
  end
  end
  def show
    @comment = comment.find(params[:id])
  end
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def comment_params
    params.require(:comment).permit(:post_id, :content, :user_id)
  end
end

app/controllers/blogs/posts_controller.rb
class Blogs::PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action:authenticate_user!, :except => [:show, :index]
  impressionist
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @category = Category.find_by_id(@post.category_id)
    @categories = Category.all.order('id')
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.all
    @post = Post.find_by_id(params[:id])
    @category = Category.find_by_id(@post.category_id)
    @categories = Category.all.order('id')
    @post.view += 1
    @post.save!
  end

  # GET /posts/new
  def new
      @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit;end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)
    @post.view = 0
    respond_to do |format|
      if @post.save
        format.html { redirect_to blogs_post_detail_path(@post.title.to_url, @post.id), notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to blogs_post_detail_path(@post.title.to_url, @post.id), notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :picture, :view,:category_id)
    end
end

app/controllers/blogs/toppage_controller.rb
class Blogs::ToppageController < ApplicationController

  def index
    @posts = Post.all
    @most_views = Post.order('view DESC').first(8)
    @newest_views = Post.order('created_at DESC').first(4)
    @categories = Category.all.order('id')
    @category = Category.first
    # @source = Nokogiri::HTML(@post.body)
    # @img = @source.css('img').map{ |i| i['src'] }.first
  end

end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/posts_helper.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  title       :string
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer
#  picture     :string
#  view        :integer
#  category_id :integer
#

module PostsHelper
end

app/views/blogs/posts/_form.html.slim
div class="panel panel-default"
  div class="panel-body"
    = form_for([:blogs, @post]) do |f|
      - if @post.errors.any?
        div id="error_explanation"
          h2
            = pluralize(@post.errors.count, "error")
            | prohibited this post from being saved:
          ul
            - @post.errors.full_messages.each do |message|
              li = message

      div class="form-group"
        = f.label :title
        br
        = f.text_field :title, autofocus: true, class: "form-control"

      div class="form-group"
        = f.label :body
        br
        = f.cktext_area :body, :class => 'someclass', :ckeditor => {:language => 'eng',:uiColor => '#9a9a9a', :toolbar => 'mini'}, class: "form-control"

      div class="form-group"
        = f.label :picture
        br
        = f.file_field :picture, class: "form-control"

      div class="form-group"
      = f.label :category_id
      br
      = f.collection_select :category_id, Category.all, :id, :name,{}, class: "form-control"

      br
      div class="actions"
        = f.submit

app/views/blogs/posts/edit.html.slim
// section#navigate.navigate-section
//   .inner-container
//     = render "blogs/toppage/navigate"
h1 Editing Post

= render 'form'

= link_to 'Show', blogs_post_path(@post), :class => "btn btn-blue btn-border-rev"
= link_to 'Back', blogs_post_path, :class => "btn btn-red btn-border-rev"

app/views/blogs/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', blogs_post_path(post)%></td>
        <td><%= link_to 'Edit', edit_blogs_post_path(post)%></td>
        <td><%= link_to 'Destroy', blogs_post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_blogs_post_path %>

app/views/blogs/posts/new.html.slim
section#navigate.navigate-section
  .inner-container
    = render "blogs/toppage/navigate"
h1 New Post

= render 'form'

= link_to 'Back', blogs_path
//

app/views/blogs/posts/show.html.slim
section#navigate.navigate-section
  .inner-container
    = render "blogs/toppage/navigate"
.body-blog.container-fluid
  .col-lg-9
    .post-detail
      .profile-userpic
        - if @post.user.avatar?
          =image_tag(@post.user.avatar)
        - else
          =image_tag('avatar-empty.png')
        .content-user
          = link_to @post.user.email, user_path(@post.user_id)
          p 
            | Posted by 
            span #{@post.user.username}
            |  on #{@post.created_at.strftime("%B #{@post.created_at.day.ordinalize}, %Y")}
      - unless notice.blank?
        div class="alert alert-success fade in"
          a href="#" class="close" data-dismiss="alert" aria-label="close" &times
          strong #{notice}!
      .title
        p
          strong #{@post.title.titleize}
      .content.content-blog
        =image_tag @post.picture
        p #{@post.body.html_safe}

      div class="fb-like" data-href= "https://protected-mountain-41572.herokuapp.com/blogs/suong-mu-huyen-ao-o-dubai/11" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"
      p.view
        strong Views: #{@post.view} |
        strong Comments: #{@post.comments.count}

      H4.title-comment Comments
      .comments
        = render :partial => @post.comments

      = simple_form_for [:blogs, @post,Comment.new] do |f|
        p
          = f.input :content, :label => "New Comment", as: :text, input_html: { rows: "3" }
        p
          = f.submit "Add Comment", class: "btn btn-primary btn-signup"
      p
        - if current_user == @post.user
          = link_to 'Edit', edit_blogs_post_path(@post), :class => "btn btn-blue btn-signup"

        = link_to 'Back', blogs_posts_path, :class => "btn btn-red btn-signup"

  .col-lg-3
    .blog
      .follow-social


      .subcribe-user
        div class="thumbnail center well well-small text-center"
          h2 Following Us
          div class="fb-follow" data-href="https://www.facebook.com/zuck" data-width="250px" data-height="100px" data-layout="standard" data-show-faces="true"
          .twitter-follow
            a.twitter-follow-button data-show-count="false" data-size="large" href="https://twitter.com/twitter"  Follow @twitter

          h2 Subscribe
          p Subscribe now to get latest blog
          form action="" method="post" role ="form"
            div class="form-group"
              span class="add-on"
                i class="icon-envelope"
                  input type="text" id="" name="" placeholder="your@email.com" class = "form-control"
                  br
                  input type = "text" placeholder="yourname" class = "form-control"
                  br
                  input type="submit" value="Subscribe Now!" class="btn btn-large"
section#footer
  .inner-container
    = render "home/footer"
div id="fb-root"
  javascript:
    !(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.5&appId=204925713178994";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
    !function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');